In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

/Users/Kunal/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/Kunal/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/Kunal/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/Kunal/anaconda3/lib/python3.6/site-packages/tensorboar

In [2]:
x = tf.constant(3, name="x") 
y = tf.constant(4, name="y") 
f=x*x*y+y+2

In [3]:
sess = tf.compat.v1.Session()


In [4]:
sess.run(f)

42

In [5]:
with tf.compat.v1.Session() as sess: 

    result = f.eval()

In [6]:
result

42

In [7]:
x = tf.Variable(3, name="x") 
y = tf.Variable(4, name="y")

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [8]:
sess = tf.compat.v1.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)

In [9]:
result

42

In [10]:
tf.Graph

tensorflow.python.framework.ops.Graph

In [11]:
x1 = tf.Variable(1)
x1.graph is tf.compat.v1.get_default_graph()

True

In [12]:
w = tf.constant(3) 
x=w+2 
y=x+5 
z=x*3
with tf.compat.v1.Session() as sess: 
    print(y.eval()) # 10 
    print(z.eval()) # 15

10
15


In [13]:
import numpy as np

In [14]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m,n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]

X = tf.constant(housing_data_plus_bias, name = "X")
y = tf.constant(housing.target.reshape(-1,1), name='y')


In [15]:
XT = tf.transpose(X)

In [16]:
theta = tf.matmul(tf.matmul(tf.linalg.inv(tf.matmul(XT, X)), XT), y)

In [17]:
with tf.compat.v1.Session() as sess: 
    theta_value = theta.eval()

In [18]:
theta_value

array([[-3.69419202e+01],
       [ 4.36693293e-01],
       [ 9.43577803e-03],
       [-1.07322041e-01],
       [ 6.45065694e-01],
       [-3.97638942e-06],
       [-3.78654265e-03],
       [-4.21314378e-01],
       [-4.34513755e-01]])

In [19]:
n_epochs = 1000
learning_rate = 0.01

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data_plus_bias = scaler.fit_transform(housing_data_plus_bias)

In [21]:
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name ="X")
y = tf.constant(housing.target.reshape(-1,1), dtype=tf.float32, name='y')

theta = tf.Variable(tf.compat.v1.random_uniform([n+1,1] , -1.0, 1.0), name = 'theta')

y_pred = tf.matmul(X,theta, name='predictions')

error = y_pred - y

mse = tf.reduce_mean(tf.square(error) , name='mse')

gradient = 2/m * tf.matmul(tf.transpose(X), error)

training_op = tf.compat.v1.assign(theta, theta - learning_rate * gradient)

init = tf.compat.v1.global_variables_initializer()

In [22]:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch%100 == 0:
            print( f"epoch = {epoch}, mse = {mse.eval()}")
        sess.run(training_op)
        
    print('done')
    best_theta = theta.eval()

epoch = 0, mse = 13.622791290283203
epoch = 100, mse = 5.105377674102783
epoch = 200, mse = 4.972999095916748
epoch = 300, mse = 4.927347183227539
epoch = 400, mse = 4.895350933074951
epoch = 500, mse = 4.871905326843262
epoch = 600, mse = 4.8546271324157715
epoch = 700, mse = 4.841855049133301
epoch = 800, mse = 4.8323845863342285
epoch = 900, mse = 4.825339317321777
done


In [23]:
best_theta

array([[-0.6815157 ],
       [ 0.86242783],
       [ 0.16449279],
       [-0.25346482],
       [ 0.2631567 ],
       [ 0.01171057],
       [-0.04389504],
       [-0.535632  ],
       [-0.50652367]], dtype=float32)

In [24]:
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name ="X")
y = tf.constant(housing.target.reshape(-1,1), dtype=tf.float32, name='y')

theta = tf.Variable(tf.compat.v1.random_uniform([n+1,1] , -1.0, 1.0), name = 'theta')

y_pred = tf.matmul(X,theta, name='predictions')

error = y_pred - y

mse = tf.reduce_mean(tf.square(error) , name='mse')

gradient = tf.gradients(mse, [theta])[0]#2/m * tf.matmul(tf.transpose(X), error)

training_op = tf.compat.v1.assign(theta, theta - learning_rate * gradient)

init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch%100 == 0:
            print( f"epoch = {epoch}, mse = {mse.eval()}")
        sess.run(training_op)
        
    print('done')
    best_theta = theta.eval()



epoch = 0, mse = 9.865930557250977
epoch = 100, mse = 5.197604179382324
epoch = 200, mse = 5.055650234222412
epoch = 300, mse = 4.986341953277588
epoch = 400, mse = 4.9368438720703125
epoch = 500, mse = 4.900911331176758
epoch = 600, mse = 4.874778747558594
epoch = 700, mse = 4.855747699737549
epoch = 800, mse = 4.841870307922363
epoch = 900, mse = 4.831734657287598
done


#### Optimizers

In [25]:
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name ="X")
y = tf.constant(housing.target.reshape(-1,1), dtype=tf.float32, name='y')

theta = tf.Variable(tf.compat.v1.random_uniform([n+1,1] , -1.0, 1.0), name = 'theta')

y_pred = tf.matmul(X,theta, name='predictions')

error = y_pred - y

mse = tf.reduce_mean(tf.square(error) , name='mse')

#gradient = tf.gradients(mse, [theta])[0]#2/m * tf.matmul(tf.transpose(X), error)

#optimizer = tf.compat.v1.train.MomentumOptimizer(learning_rate=learning_rate, momentum=0.9)
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=learning_rate )

training_op = optimizer.minimize(mse)

init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch%100 == 0:
            print( f"epoch = {epoch}, mse = {mse.eval()}")
        sess.run(training_op)
        
    print('done')
    best_theta = theta.eval()



epoch = 0, mse = 9.17242431640625
epoch = 100, mse = 5.074120998382568
epoch = 200, mse = 4.963111877441406
epoch = 300, mse = 4.919527530670166
epoch = 400, mse = 4.8884711265563965
epoch = 500, mse = 4.8658576011657715
epoch = 600, mse = 4.8493571281433105
epoch = 700, mse = 4.837296962738037
epoch = 800, mse = 4.82846736907959
epoch = 900, mse = 4.821987628936768
done


#### Mini batch gradient descent

In [26]:
A=tf.compat.v1.placeholder(tf.float32, shape=(None,3))
B=A+5

with tf.compat.v1.Session() as sess:
    B_val_1 = B.eval(feed_dict={A:[[1,2,3]]})
    B_val_2 = B.eval(feed_dict={A:[[4,5,6],[7,8,9]]})

In [27]:
B_val_1

array([[6., 7., 8.]], dtype=float32)

In [28]:
B_val_2

array([[ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

In [29]:
import tensorflow.compat.v1 as old_tf

In [30]:
X = old_tf.placeholder(dtype=tf.float32, shape=(None, None), name='X')
y = old_tf.placeholder(dtype=tf.float32, shape=(None,None), name='y')

In [31]:
batch_size = 100
n_batches = int(np.ceil(m/batch_size))

In [32]:
def fetch_batch(epoch, batch_index, batch_size): # load the data from disk
    start = batch_index*batch_size
    X_batch = scaled_housing_data_plus_bias[start : start + batch_size ]
    y_batch = housing.target[start : start + batch_size].reshape(-1,1)

    return X_batch, y_batch

In [ ]:
theta = tf.Variable(old_tf.random_uniform([n+1,1] , -1.0, 1.0), name = 'theta')



y_pred = tf.matmul(X,theta, name='predictions')

error = y_pred - y

mse = tf.reduce_mean(tf.square(error) , name='mse')

#gradient = tf.gradients(mse, [theta])[0]#2/m * tf.matmul(tf.transpose(X), error)

#optimizer = tf.compat.v1.train.MomentumOptimizer(learning_rate=learning_rate, momentum=0.9)
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=learning_rate )

training_op = optimizer.minimize(mse)

init = tf.compat.v1.global_variables_initializer()

In [33]:
with old_tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size )

            if epoch%100 == 0:
                print( f"epoch = {epoch}, mse = {mse.eval()}")

            sess.run(training_op, feed_dict = {X:X_batch, y:y_batch})
        
        
    print('done')
    best_theta = theta.eval()

epoch = 0, mse = 9.135147094726562
epoch = 0, mse = 8.869178771972656
epoch = 0, mse = 8.620494842529297
epoch = 0, mse = 8.387917518615723
epoch = 0, mse = 8.1703519821167
epoch = 0, mse = 7.966780185699463
epoch = 0, mse = 7.7762579917907715
epoch = 0, mse = 7.597906112670898
epoch = 0, mse = 7.430907726287842
epoch = 0, mse = 7.274501323699951
epoch = 0, mse = 7.127982139587402
epoch = 0, mse = 6.990693092346191
epoch = 0, mse = 6.862020015716553
epoch = 0, mse = 6.741396427154541
epoch = 0, mse = 6.628291606903076
epoch = 0, mse = 6.522212028503418
epoch = 0, mse = 6.422695636749268
epoch = 0, mse = 6.329319000244141
epoch = 0, mse = 6.241681098937988
epoch = 0, mse = 6.15941047668457
epoch = 0, mse = 6.082160472869873
epoch = 0, mse = 6.009608745574951
epoch = 0, mse = 5.941452980041504
epoch = 0, mse = 5.877416610717773
epoch = 0, mse = 5.817233085632324
epoch = 0, mse = 5.7606587409973145
epoch = 0, mse = 5.707467079162598
epoch = 0, mse = 5.657443523406982
epoch = 0, mse = 5.61

epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
epoch = 100, mse = 4.803253650665283
e

epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
epoch = 300, mse = 4.803253650665283
e

epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
epoch = 400, mse = 4.803253650665283
e

epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
epoch = 600, mse = 4.803253650665283
e

epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
epoch = 700, mse = 4.803253650665283
e

epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
epoch = 900, mse = 4.803253650665283
e

In [ ]:
y